### ISSUE TITLE
Wrong result

### ISSUE THREAD

**Issue by wangjiyuan9** [duanyiqun/DiffusionDepth#46]
<img width="1607" alt="image" src="https://github.com/duanyiqun/DiffusionDepth/assets/47146885/7d9dd294-1e49-4e67-9b05-4974c88a6a17">
Could you tell me why the result is like that? I really follow your constructions strictly.

**Comment by duanyiqun** [comment]
Hi there, 

Sorry for a late reply since recently I'm too jammed by other projects and will be not able look into every issue. 
It's unusual to see this curve, it's usually as shown below. Probably increasing the batch size would help.  
![image](https://github.com/duanyiqun/DiffusionDepth/assets/27565147/bb071471-7643-4168-a8f5-4cfddd214509)

Best regards
Yiqun

**Comment by ZhouCX117** [comment]
@wangjiyuan9 Hi, sorry to bother you. Could you please provide the environment you used? The provided requirement does not work, and I have tried several times.
